## Numpy
```
Q) Difference between Python List and Numpy array?
Ans) numpy array is a list which contains elements of same data type only
```

In [1]:
import numpy as np

In [2]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularl

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'a

The main feature of numpy is array object class. Arrays are similar to lists, except that every element in an array must be of the same type.

In [4]:
my_array = np.array([1, 5, 7, 9])

my_array

array([1, 5, 7, 9])

In [5]:
type(my_array) 

numpy.ndarray

In [6]:
my_array.dtype # type of elements in array

dtype('int32')

In [7]:
my_array = np.array([1, 5, 7, 9], float)

my_array

array([1., 5., 7., 9.])

In [8]:
my_array.dtype # type of elements in array

dtype('float64')

In [9]:
len(my_array)

4

In [10]:
my_array.shape

(4,)

Multi-dimensional Arrays

In [11]:
myary = np.array([(1, 2, 3), 
                  (5, 6, 7)], float)

myary

array([[1., 2., 3.],
       [5., 6., 7.]])

In [12]:
myary.shape

(2, 3)

In [13]:
len(myary)

2

In [14]:
my_array = np.arange(15)

In [15]:
print(my_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
my_array.shape

(15,)

In [17]:
my_array.ndim  # the number of axes (dimensions) of the array.

1

In [18]:
my_array1 = my_array.reshape(3, 5)

print(my_array1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [19]:
my_array1.shape

(3, 5)

In [20]:
my_array1.ndim

2

In [21]:
my_array1.dtype.name

'int32'

**ndarray.itemsize**
```
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
```

In [22]:
my_array1.itemsize

4

In [23]:
my_array1.size

15

In [24]:
type(my_array1)

numpy.ndarray

### Array Creation

In [25]:
my_array2 = np.array([6, 7, 8])

In [26]:
my_array2

array([6, 7, 8])

In [27]:
print(my_array2)

[6 7 8]


In [28]:
my_array2.dtype

dtype('int32')

In [29]:
type(my_array2)

numpy.ndarray

In [30]:
my_array3 = np.array([1.2, 3.5, 5.1])
print('my_array3.dtype', my_array3.dtype)
print('type(my_array3)', type(my_array3))

my_array3.dtype float64
type(my_array3) <class 'numpy.ndarray'>


In [31]:
np.array([(1.5,2,3), (4,5,6)])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [32]:
my_array3 = np.array( [ [1,2], [3,4] ], dtype=complex )

In [33]:
my_array3

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

_zeros_like_ and _ones_like_ functions create a new array with the same dimensions and type of an existing one:

In [34]:
np.zeros_like(my_array3)

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

In [35]:
np.ones_like(my_array3)

array([[1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j]])

In [36]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [38]:
print(np.ones( (2,3,4), dtype=np.int16 ) )

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [39]:
np.ones((2,2)) * 7

array([[7., 7.],
       [7., 7.]])

In [40]:
np.ones((2,2), dtype=np.int16) * 7

array([[7, 7],
       [7, 7]], dtype=int16)

In [41]:
np.full((2,2), 7)        # Create a constant array

array([[7, 7],
       [7, 7]])

In [42]:
np.eye(2)                # unit 2x2 matrix; "eye" represents "I"

array([[1., 0.],
       [0., 1.]])

The eye function returns matrices with ones along the kth diagonal:

In [43]:
np.eye(4, k=0, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
np.eye(4, k=1, dtype=float)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [45]:
np.eye(4, k=2, dtype=float)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
np.eye(4, k=-1, dtype=float)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [47]:
np.identity(4, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.identity(6, dtype=float)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [49]:
np.random.random((2,3))  # Create an array filled with random values

array([[0.61032154, 0.86392377, 0.09793669],
       [0.89407221, 0.70614186, 0.28528395]])

In [50]:
np.empty( (2,3) )        # uninitialized, output may vary

array([[0.61032154, 0.86392377, 0.09793669],
       [0.89407221, 0.70614186, 0.28528395]])

In [51]:
np.empty( (2,3) )  

array([[0.61032154, 0.86392377, 0.09793669],
       [0.89407221, 0.70614186, 0.28528395]])

In [52]:
np.random.random((2,3))

array([[0.15689849, 0.73414087, 0.44435737],
       [0.22435974, 0.72764077, 0.11198016]])

In [53]:
np.empty( (2,3) )  

array([[0.15689849, 0.73414087, 0.44435737],
       [0.22435974, 0.72764077, 0.11198016]])

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.



In [54]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [55]:
np.arange( 0, 2, 0.3 )                 # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [56]:
np.arange( 0.4, 2.2, 0.3 )             # It accepts float start and final values

array([0.4, 0.7, 1. , 1.3, 1.6, 1.9, 2.2])

In [57]:
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [58]:
np.linspace( 0, 2, 10 ) 

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [59]:
np.linspace( 0, 2, 5 ) 

array([0. , 0.5, 1. , 1.5, 2. ])

In [60]:
x = np.linspace(0,  2* np.pi, 100 )        # useful to evaluate function at lots of points
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [61]:
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [62]:
print(np.arange(10000))  # for large data, nupy skips displaying intermediate values

[   0    1    2 ... 9997 9998 9999]


In [63]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


if we need to disable this displaying behaviour, use 
> __np.set_printoptions(threshold=np.nan)__

##### Automatic Re-shaping

In [64]:
a = np.arange(30)

In [65]:
a.shape

(30,)

In [66]:
a.shape = 2,-1,3  # -1 means "whatever is needed"

In [67]:
a.shape

(2, 5, 3)

In [68]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

### Basic Operations

In [69]:
a = np.array( [20,30,40,50] )
a

array([20, 30, 40, 50])

In [70]:
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [71]:
a + b

array([20, 31, 42, 53])

In [72]:
a -b

array([20, 29, 38, 47])

In [73]:
a * b

array([  0,  30,  80, 150])

In [74]:
b / a

array([0.        , 0.03333333, 0.05      , 0.06      ])

In [75]:
a % b

<ipython-input-75-bb5d1a9b79f9>:1: RuntimeWarning: divide by zero encountered in remainder
  a % b


array([0, 0, 0, 2], dtype=int32)

In [76]:
b % a

array([0, 1, 2, 3], dtype=int32)

In [77]:
b ** a

array([         0,          1,          0, -794958903], dtype=int32)

In [78]:
b ** 2

array([0, 1, 4, 9], dtype=int32)

In [79]:
d = np.arange(3)
d

array([0, 1, 2])

In [80]:
a - d

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
10 * np.sin(a)  # element-wise multiplication

In [ ]:
a, a < 35

In [ ]:
A = np.array( [[1,1],
               [0,1]] )

B = np.array( [[2,0],
               [3,4]] )

In [ ]:
A * B                       # elementwise product

In [ ]:
A @ B                       # matrix product  - works only in Python >= 3.5

In [ ]:
A.dot(B)                    # another matrix product

In [ ]:
a = np.ones((2,3), dtype=int)
a

In [ ]:
a *= 3

In [ ]:
a

In [ ]:
b = np.random.random((2,3))
b += a

In [ ]:
b

In [ ]:
a += b           # b is not automatically converted to integer type

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [ ]:
a = np.ones(3, dtype=np.int32)
a

In [ ]:
b = np.linspace(0,np.pi,3)
print(b,  b.dtype.name)

In [ ]:
c = a+b

In [ ]:
c

In [ ]:
c.dtype.name

In [ ]:
c*1j

In [ ]:
d = np.exp(c*1j)

In [ ]:
d

In [ ]:
d.dtype.name

In [ ]:
a = np.array([2, 4, 3, 34, 324, 213, 12, 23, 34, 45, 67, -234], float)

In [ ]:
a.min()       # min of each row

In [ ]:
a.max()

In [ ]:
a.sum()        # sum of each column

In [ ]:
a.prod()    # product of each element

Alternatively, 

In [ ]:
np.sum(a)

In [ ]:
np.prod(a)

Statistical quantities

In [ ]:
a.mean()

In [ ]:
a.var()

In [ ]:
a.std()

The argmin and argmax functions return the array indices of the minimum and maximum
values

In [ ]:
a = np.array([2, 4, 3, 34, 324, 213, 12, 23, 34, 45, 67, -234], float)
#             0  1  2   3   4    5    6   7   8   9  10    11
print(f'a.argmin(): {a.argmin()}')
print(f'a.argmax(): {a.argmax()}')

In [ ]:
a = np.array([[0, 2], [3, -1], [3, 5]], float)

print(f'a.mean(axis=0):{a.mean(axis=0)}')
print(f'a.mean(axis=1):{a.mean(axis=1)}')

In [ ]:
print(f'a.min(axis=0):{a.min(axis=0)}')
print(f'a.min(axis=1):{a.min(axis=1)}')

In [ ]:
print(f'a.max(axis=0):{a.max(axis=0)}')
print(f'a.max(axis=1):{a.max(axis=1)}')

In [ ]:
a = np.array([6, 2, 5, -1, 0], float)
print(f'sorted(a): {sorted(a)}')
print(f'a        : {a}')

In [ ]:
a.sort()
a

Values in an array can be "clipped" to be within a prespecified range. This is the same as
applying min(max(x, minval), maxval) to each element x in an array.

In [ ]:
a = np.array([6, 2, 5, -1, 0], float)
a.clip(0, 5)

Unique elements can be extracted from an array:

In [ ]:
a = np.array([1, 1, 4, 5, 5, 5, 7], float)
np.unique(a)

For two dimensional arrays, the diagonal can be extracted:

In [ ]:
a = np.array([[1, 2], 
              [3, 4]], float)
a.diagonal()

In [ ]:
x = np.array([[1,2],[3,4]])

print(x, np.sum(x))          # Compute sum of all elements; prints "10"

In [ ]:
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"

In [ ]:
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

In [ ]:
b = np.arange(12).reshape(3,4)

In [ ]:
b

In [ ]:
b.cumsum(axis=1)                         # cumulative sum along each row

In [ ]:
b.cumsum(axis=0)                         # cumulative sum along each row

In [ ]:
b.cumsum()

In [ ]:
B = np.arange(3)
B

In [ ]:
np.exp(B)

In [ ]:
np.sqrt(B)

In [ ]:
C = np.array([2., -1., 4.])
C

In [ ]:
np.add(B, C)

In [ ]:
B + C

### Array concatenation

In [ ]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)

np.concatenate((a, b, c))

In [ ]:
a + b + c

If an array has more than one dimension, it is possible to specify the axis along which multiple
arrays are concatenated. By default (without specifying the axis), NumPy concatenates along
the first dimension:

In [ ]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)

In [ ]:
np.concatenate(a,b)

In [ ]:
np.concatenate((a,b))

In [ ]:
np.concatenate((a,b), axis=0)

In [ ]:
np.concatenate((a,b), axis=1)

### Indexing, Slicing and Iterating

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.



In [ ]:
a = np.arange(10) ** 3

In [ ]:
a

In [ ]:
a[2]

In [ ]:
a[2:5]

In [ ]:
a[:6:2]

In [ ]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000

In [ ]:
print(a)

In [ ]:
a[ : :-1]                                 # reversed a

In [ ]:
for i in a:
    print(i**(1/3.))

In [ ]:
m = np.array([[1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12]])

In [ ]:
m

In [ ]:
n = m[:2, 1:3]

In [ ]:
n

In [ ]:
m[0, 1]

In [ ]:
n[0, 0] = 77     # n[0, 0] is the same piece of data as m[0, 1]
n

In [ ]:
m[0, 1]

In [ ]:
m

Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [ ]:
def f(x,y):
    return 10 *x + y

b = np.fromfunction(f,(5,4),dtype=int)

In [ ]:
b

In [ ]:
b[2,3]

In [ ]:
b[0:5, 1]                       # each row in the second column of b

In [ ]:
b[ : ,1]                        # equivalent to the previous example

In [ ]:
b[1:3, : ]                      # each column in the second and third row of b

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [ ]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

In [ ]:
c = np.array( [
    [ [  0,  1,  2],               # a 3D array (two stacked 2D arrays)
      [ 10, 12, 13]
    ],
    [ [100,101,102],
      [110,112,113]
    ]
])

In [ ]:
c.shape

In [ ]:
c[1,...]                                   # same as c[1,:,:] or c[1]

In [ ]:
c[...,2]                                   # same as c[:,:,2]

Iterating over multidimensional arrays is done with respect to the first axis:

In [ ]:
for row in b:
    print(row)

In [ ]:
b.flat, type(b.flat)

In [ ]:
b.flatten()

In [ ]:
b

In [ ]:
b.shape

In [ ]:
b = b.reshape(1, 20)
b

### Shape Manipulation

##### Changing the shape of an array

In [ ]:
a = np.floor(10 * np.random.random((3,4))) 

In [ ]:
a

In [ ]:
a.shape

In [ ]:
a.flatten()

In [ ]:
a

In [ ]:
a.ravel()  # returns the array, flattened

In [ ]:
a

In [ ]:
a.reshape(6,2)  # returns the array with a modified shape

In [ ]:
a.T  # returns the array, transposed

In [ ]:
a.T.shape

In [ ]:
a.shape

In [ ]:
a

In [ ]:
a.resize((2,6))
a

If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

In [ ]:
a.reshape(3,-1)

##### Stacking together different arrays
Several arrays can be stacked together along different axes:


In [ ]:
x = np.arange(0,10,2)                     # x=([0,2,4,6,8])
y = np.arange(5)                          # y=([0,1,2,3,4])

In [ ]:
x

In [ ]:
y

In [ ]:
np.vstack([x,y])

In [ ]:
np.hstack([x,y]) 

In [ ]:
a = np.floor(10*np.random.random((2,2)))
a

In [ ]:
b = np.floor(10*np.random.random((2,2)))
b

In [ ]:
np.vstack((a,b))        # Horizontal Append

In [ ]:
np.hstack((a,b))        # Vertical Append

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:

In [ ]:
np.column_stack((a,b))     # with 2D arrays

In [ ]:
a = np.array([4.,2.])
b = np.array([3.,8.])

In [81]:
np.column_stack((a,b))     # returns a 2D array

array([[20,  0],
       [30,  1],
       [40,  2],
       [50,  3]])

In [82]:
np.hstack((a,b))           # the result is different

array([20, 30, 40, 50,  0,  1,  2,  3])

In [83]:
np.vstack((a,b)) 

array([[20, 30, 40, 50],
       [ 0,  1,  2,  3]])

In [84]:
from numpy import newaxis
a[:,newaxis]               # this allows to have a 2D columns vector

array([[20],
       [30],
       [40],
       [50]])

In [85]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[20,  0],
       [30,  1],
       [40,  2],
       [50,  3]])

In [86]:
np.hstack((a[:,newaxis],b[:,newaxis]))   # the result is the same

array([[20,  0],
       [30,  1],
       [40,  2],
       [50,  3]])

##### Splitting one array into several smaller ones

In [87]:
a = np.floor(10*np.random.random((2,12)))

In [88]:
a

array([[4., 7., 3., 5., 3., 5., 1., 9., 1., 4., 6., 5.],
       [2., 5., 0., 8., 8., 7., 1., 4., 2., 4., 7., 2.]])

In [89]:
print(np.hsplit(a,3))   # Split a into 3

[array([[4., 7., 3., 5.],
       [2., 5., 0., 8.]]), array([[3., 5., 1., 9.],
       [8., 7., 1., 4.]]), array([[1., 4., 6., 5.],
       [2., 4., 7., 2.]])]


In [90]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[4., 7., 3.],
        [2., 5., 0.]]),
 array([[5.],
        [8.]]),
 array([[3., 5., 1., 9., 1., 4., 6., 5.],
        [8., 7., 1., 4., 2., 4., 7., 2.]])]

vsplit splits along the vertical axis, and array_split allows one to specify along which axis to split.



### Copies and Views
##### No Copy at All
Simple assignments make no copy of array objects or of their data.



In [91]:
a = np.arange(12)

In [92]:
b = a            # no new object is created

In [93]:
b is a           # a and b are two names for the same ndarray object

True

In [94]:
id(a), id(b)

(1985342584832, 1985342584832)

In [95]:
b.shape = 3,4    # changes the shape of a
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
a.shape

(3, 4)

Python passes mutable objects as references, so function calls make no copy.



In [97]:
def f(x):
    print(id(x))

In [98]:
id(a)                           # id is a unique identifier of an object

1985342584832

In [99]:
f(a)

1985342584832


##### View or Shallow Copy
Different array objects can share the same data. The view method creates a new array object that looks at the same data.



In [100]:
c = a.view()

In [101]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
c is a

False

In [103]:
id(a), id(b), id(c)

(1985342584832, 1985342584832, 1985341883136)

In [104]:
c.base is a                        # c is a view of the data owned by a

True

In [105]:
c.flags.owndata

False

In [106]:
c.shape = 2,6                      # a's shape doesn't change

In [107]:
a.shape

(3, 4)

In [108]:
c[0,4] = 1234                      # a's data changes

In [109]:
print(c)

[[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]


In [110]:
print(a)

[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


Slicing an array returns a view of it:



In [111]:
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"

In [112]:
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10

In [113]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

#### Deep Copy
The copy method makes a complete copy of the array and its data.



In [114]:
d = a.copy()                          # a new array object with new data is created

In [115]:
d is a

False

In [116]:
d.base is a                           # d doesn't share anything with a

False

In [117]:
d.flags.owndata

True

In [118]:
d[0,0] = 9999

In [119]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

### Broadcasting rules

Broadcasting allows universal functions to deal in a meaningful way with inputs that do not have exactly the same shape.

The first rule of broadcasting is that if all input arrays do not have the same number of dimensions, a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

The second rule of broadcasting ensures that arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is assumed to be the same along that dimension for the “broadcast” array.

After application of the broadcasting rules, the sizes of all arrays must match.

#### Indexing with Arrays of Indices

In [120]:
a = np.arange(12)**2                       # the first 12 square numbers
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [121]:
i = np.array( [ 1,1,3,8,5 ] )              # an array of indices

In [122]:
a[i]

array([ 1,  1,  9, 64, 25], dtype=int32)

In [123]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )      # a bidimensional array of indices

In [124]:
a[j]                                       # the same shape as j

array([[ 9, 16],
       [81, 49]], dtype=int32)

In [125]:
palette = np.array( [ [0,0,0],                # black
                       [255,0,0],              # red
                       [0,255,0],              # green
                       [0,0,255],              # blue
                       [255,255,255] ] )       # white

image = np.array( [ [ 0, 1, 2, 0 ],           # each value corresponds to a color in the palette
                     [ 0, 3, 4, 0 ]  ] )

print(palette[image])                            # the (2,4,3) color image


[[[  0   0   0]
  [255   0   0]
  [  0 255   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0 255]
  [255 255 255]
  [  0   0   0]]]


#### Simple Array Operations

In [126]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])

In [127]:
a

array([[1., 2.],
       [3., 4.]])

In [128]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [129]:
print(dir(np.linalg))

['LinAlgError', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_umath_linalg', 'absolute_import', 'cholesky', 'cond', 'det', 'division', 'eig', 'eigh', 'eigvals', 'eigvalsh', 'inv', 'lapack_lite', 'linalg', 'lstsq', 'matrix_power', 'matrix_rank', 'multi_dot', 'norm', 'pinv', 'print_function', 'qr', 'slogdet', 'solve', 'svd', 'tensorinv', 'tensorsolve', 'test']


In [130]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [131]:
u = np.eye(2) # unit 2x2 matrix; "eye" represents "I"

In [132]:
u

array([[1., 0.],
       [0., 1.]])

In [133]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

In [134]:
j @ j        # matrix product  - WORKS ONLY IN PYTHON > 3.4

array([[-1.,  0.],
       [ 0., -1.]])

In [135]:
np.trace(u)  # trace - summation of principal diagonal eleements

2.0

In [136]:
y = np.array([[5.], [7.]])

In [137]:
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [138]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))