## Numpy
```
Q) Difference between Python List and Numpy array?
Ans) numpy array is a list which contains elements of same data type only
```

In [1]:
import numpy as np

In [2]:
my_array = np.arange(15)

In [3]:
print my_array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
my_array.shape

(15L,)

In [5]:
my_array.ndim  # the number of axes (dimensions) of the array.

1

In [6]:
my_array1 = my_array.reshape(3, 5)

In [7]:
print my_array1

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [8]:
my_array1.shape

(3L, 5L)

In [9]:
my_array1.ndim

2

In [10]:
my_array1.dtype.name

'int32'

**ndarray.itemsize**
```
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
```

In [11]:
my_array1.itemsize

4

In [12]:
my_array1.size

15

In [13]:
type(my_array1)

numpy.ndarray

### Array Creation

In [14]:
my_array2 = np.array([6, 7, 8])

In [15]:
my_array2

array([6, 7, 8])

In [16]:
print my_array2

[6 7 8]


In [17]:
my_array2.dtype

dtype('int32')

In [18]:
type(my_array2)

numpy.ndarray

In [19]:
my_array3 = np.array([1.2, 3.5, 5.1])
print 'my_array3.dtype', my_array3.dtype
print 'type(my_array3)', type(my_array3)

my_array3.dtype float64
type(my_array3) <type 'numpy.ndarray'>


In [20]:
np.array([(1.5,2,3), (4,5,6)])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [21]:
my_array3 = np.array( [ [1,2], [3,4] ], dtype=complex )

In [22]:
my_array3

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [23]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [25]:
print np.ones( (2,3,4), dtype=np.int16 ) 

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [26]:
np.empty( (2,3) )                                 # uninitialized, output may vary

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

In [27]:
np.empty( (2,3) )  

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.



In [28]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [29]:
np.arange( 0, 2, 0.3 )                 # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [30]:
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
x = np.linspace( 0, 2* np.pi, 100 )        # useful to evaluate function at lots of points

In [32]:
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [33]:
f = np.sin(x)

In [34]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [35]:
print(np.arange(10000))  # for large data, nupy skips displaying intermediate values

[   0    1    2 ... 9997 9998 9999]


In [36]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


if we need to disable this displaying behaviour, use 
> __np.set_printoptions(threshold=np.nan)__

### Basic Operations

In [37]:
a = np.array( [20,30,40,50] )

In [38]:
b = np.arange( 4 )

In [39]:
b

array([0, 1, 2, 3])

In [40]:
c = a - b

In [41]:
c

array([20, 29, 38, 47])

In [42]:
d = np.arange(3)

In [43]:
a - d

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [44]:
b**2

array([0, 1, 4, 9])

In [45]:
10*np.sin(a)  # element-wise multiplication

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [46]:
a<35

array([ True,  True, False, False])

In [47]:
A = np.array( [[1,1],
               [0,1]] )

B = np.array( [[2,0],
               [3,4]] )

In [48]:
A * B                       # elementwise product

array([[2, 0],
       [0, 4]])

In [49]:
A @ B                       # matrix product  - works only in Python >= 3.5

SyntaxError: invalid syntax (<ipython-input-49-ad05aaac1a13>, line 1)

In [50]:
A.dot(B)                    # another matrix product

array([[5, 4],
       [3, 4]])

In [51]:
a = np.ones((2,3), dtype=int)

In [52]:
a *= 3

In [53]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [54]:
b = np.random.random((2,3))
b += a

In [55]:
b

array([[3.28377885, 3.74777041, 3.16615515],
       [3.07872288, 3.60039673, 3.64230337]])

In [56]:
a += b           # b is not automatically converted to integer type

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [57]:
a = np.ones(3, dtype=np.int32)

In [59]:
b = np.linspace(0,np.pi,3)
print b.dtype.name

float64


In [60]:
c = a+b

In [61]:
c

array([1.        , 2.57079633, 4.14159265])

In [62]:
c.dtype.name

'float64'

In [63]:
d = np.exp(c*1j)

In [64]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [65]:
d.dtype.name

'complex128'

In [66]:
d.sum()        # sum of each column

(-0.8414709848078966+0.5403023058681399j)

In [67]:
d.min()       # min of each row

(-0.8414709848078965+0.5403023058681398j)

In [68]:
d.max()

(0.5403023058681397+0.8414709848078965j)

In [71]:
b = np.arange(12).reshape(3,4)

In [72]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])