## Numpy
```
Q) Difference between Python List and Numpy array?
Ans) numpy array is a list which contains elements of same data type only
```

In [1]:
import numpy as np

In [2]:
my_array = np.arange(15)

In [3]:
print my_array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
my_array.shape

(15L,)

In [5]:
my_array.ndim  # the number of axes (dimensions) of the array.

1

In [6]:
my_array1 = my_array.reshape(3, 5)

In [7]:
print my_array1

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [8]:
my_array1.shape

(3L, 5L)

In [9]:
my_array1.ndim

2

In [10]:
my_array1.dtype.name

'int32'

**ndarray.itemsize**
```
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
```

In [11]:
my_array1.itemsize

4

In [12]:
my_array1.size

15

In [13]:
type(my_array1)

numpy.ndarray

### Array Creation

In [14]:
my_array2 = np.array([6, 7, 8])

In [15]:
my_array2

array([6, 7, 8])

In [16]:
print my_array2

[6 7 8]


In [17]:
my_array2.dtype

dtype('int32')

In [18]:
type(my_array2)

numpy.ndarray

In [19]:
my_array3 = np.array([1.2, 3.5, 5.1])
print 'my_array3.dtype', my_array3.dtype
print 'type(my_array3)', type(my_array3)

my_array3.dtype float64
type(my_array3) <type 'numpy.ndarray'>


In [20]:
np.array([(1.5,2,3), (4,5,6)])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [21]:
my_array3 = np.array( [ [1,2], [3,4] ], dtype=complex )

In [22]:
my_array3

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [23]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [25]:
print np.ones( (2,3,4), dtype=np.int16 ) 

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [26]:
np.empty( (2,3) )                                 # uninitialized, output may vary

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

In [27]:
np.empty( (2,3) )  

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.



In [28]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [29]:
np.arange( 0, 2, 0.3 )                 # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [30]:
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
x = np.linspace( 0, 2* np.pi, 100 )        # useful to evaluate function at lots of points

In [32]:
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [33]:
f = np.sin(x)

In [34]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [35]:
print(np.arange(10000))  # for large data, nupy skips displaying intermediate values

[   0    1    2 ... 9997 9998 9999]


In [36]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


if we need to disable this displaying behaviour, use 
> __np.set_printoptions(threshold=np.nan)__

### Basic Operations

In [37]:
a = np.array( [20,30,40,50] )

In [38]:
b = np.arange( 4 )

In [39]:
b

array([0, 1, 2, 3])

In [40]:
c = a - b

In [41]:
c

array([20, 29, 38, 47])

In [42]:
d = np.arange(3)

In [43]:
a - d

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [44]:
b**2

array([0, 1, 4, 9])

In [45]:
10*np.sin(a)  # element-wise multiplication

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [46]:
a<35

array([ True,  True, False, False])

In [47]:
A = np.array( [[1,1],
               [0,1]] )

B = np.array( [[2,0],
               [3,4]] )

In [48]:
A * B                       # elementwise product

array([[2, 0],
       [0, 4]])

In [49]:
A @ B                       # matrix product  - works only in Python >= 3.5

SyntaxError: invalid syntax (<ipython-input-49-72ebf3a5228a>, line 1)

In [50]:
A.dot(B)                    # another matrix product

array([[5, 4],
       [3, 4]])

In [51]:
a = np.ones((2,3), dtype=int)

In [52]:
a *= 3

In [53]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [54]:
b = np.random.random((2,3))
b += a

In [55]:
b

array([[3.77219211, 3.18940598, 3.30350078],
       [3.71208557, 3.46807563, 3.16185642]])

In [56]:
a += b           # b is not automatically converted to integer type

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [57]:
a = np.ones(3, dtype=np.int32)

In [58]:
b = np.linspace(0,np.pi,3)
print b.dtype.name

float64


In [59]:
c = a+b

In [60]:
c

array([1.        , 2.57079633, 4.14159265])

In [61]:
c.dtype.name

'float64'

In [62]:
d = np.exp(c*1j)

In [63]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [64]:
d.dtype.name

'complex128'

In [65]:
d.sum()        # sum of each column

(-0.8414709848078966+0.5403023058681399j)

In [66]:
d.min()       # min of each row

(-0.8414709848078965+0.5403023058681398j)

In [67]:
d.max()

(0.5403023058681397+0.8414709848078965j)

In [68]:
b = np.arange(12).reshape(3,4)

In [69]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [71]:
B = np.arange(3)

In [72]:
B

array([0, 1, 2])

In [73]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [74]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [75]:
C = np.array([2., -1., 4.])

In [76]:
np.add(B, C)

array([2., 0., 6.])

### Indexing, Slicing and Iterating

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.



In [77]:
a = np.arange(10)**3

In [78]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [79]:
a[2]

8

In [80]:
a[2:5]

array([ 8, 27, 64])

In [81]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000

In [82]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [83]:
a[ : :-1]                                 # reversed a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [84]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


c:\python27\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [85]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)

In [86]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [87]:
b[2,3]

23

In [88]:
b[0:5, 1]                       # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [89]:
b[ : ,1]                        # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [90]:
b[1:3, : ]                      # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [91]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

In [92]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                 [ 10, 12, 13]],
                [[100,101,102],
                 [110,112,113]]])

In [93]:
c.shape

(2L, 2L, 3L)

In [94]:
c[1,...]                                   # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [95]:
c[...,2]                                   # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

Iterating over multidimensional arrays is done with respect to the first axis:

In [96]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [97]:
b.flat

In [98]:
b.flatten

<function flatten>

In [99]:
b.flatten()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

### Shape Manipulation

##### Changing the shape of an array

In [100]:
a = np.floor(10 * np.random.random((3,4))) 

In [101]:
a

array([[9., 1., 4., 8.],
       [4., 5., 2., 9.],
       [9., 3., 1., 0.]])

In [102]:
a.shape

(3L, 4L)

In [103]:
a.ravel()  # returns the array, flattened

array([9., 1., 4., 8., 4., 5., 2., 9., 9., 3., 1., 0.])

In [104]:
a.reshape(6,2)  # returns the array with a modified shape

array([[9., 1.],
       [4., 8.],
       [4., 5.],
       [2., 9.],
       [9., 3.],
       [1., 0.]])

In [105]:
a.T  # returns the array, transposed

array([[9., 4., 9.],
       [1., 5., 3.],
       [4., 2., 1.],
       [8., 9., 0.]])

In [106]:
a.T.shape

(4L, 3L)

In [107]:
a.shape

(3L, 4L)

In [108]:
a

array([[9., 1., 4., 8.],
       [4., 5., 2., 9.],
       [9., 3., 1., 0.]])

In [109]:
a.resize((2,6))

If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

In [110]:
a.reshape(3,-1)

array([[9., 1., 4., 8.],
       [4., 5., 2., 9.],
       [9., 3., 1., 0.]])

##### Stacking together different arrays
Several arrays can be stacked together along different axes:


In [111]:
a = np.floor(10*np.random.random((2,2)))
a

array([[9., 3.],
       [2., 0.]])

In [112]:
b = np.floor(10*np.random.random((2,2)))
b

array([[6., 8.],
       [1., 3.]])

In [113]:
np.vstack((a,b))        # Horizontal Append

array([[9., 3.],
       [2., 0.],
       [6., 8.],
       [1., 3.]])

In [114]:
np.hstack((a,b))        # Vertical Append

array([[9., 3., 6., 8.],
       [2., 0., 1., 3.]])

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:

In [115]:
from numpy import newaxis
np.column_stack((a,b))     # with 2D arrays

array([[9., 3., 6., 8.],
       [2., 0., 1., 3.]])

In [116]:
a = np.array([4.,2.])
b = np.array([3.,8.])

In [117]:
np.column_stack((a,b))     # returns a 2D array

array([[4., 3.],
       [2., 8.]])

In [118]:
np.hstack((a,b))           # the result is different

array([4., 2., 3., 8.])

In [119]:
a[:,newaxis]               # this allows to have a 2D columns vector

array([[4.],
       [2.]])

In [120]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [121]:
np.hstack((a[:,newaxis],b[:,newaxis]))   # the result is the same

array([[4., 3.],
       [2., 8.]])

##### Splitting one array into several smaller ones

In [122]:
a = np.floor(10*np.random.random((2,12)))

In [123]:
a

array([[0., 9., 8., 1., 0., 4., 9., 8., 1., 8., 2., 1.],
       [1., 8., 9., 3., 6., 7., 4., 3., 2., 8., 7., 6.]])

In [124]:
np.hsplit(a,3)   # Split a into 3

[array([[0., 9., 8., 1.],
        [1., 8., 9., 3.]]), array([[0., 4., 9., 8.],
        [6., 7., 4., 3.]]), array([[1., 8., 2., 1.],
        [2., 8., 7., 6.]])]

In [125]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[0., 9., 8.],
        [1., 8., 9.]]), array([[1.],
        [3.]]), array([[0., 4., 9., 8., 1., 8., 2., 1.],
        [6., 7., 4., 3., 2., 8., 7., 6.]])]

vsplit splits along the vertical axis, and array_split allows one to specify along which axis to split.



### Copies and Views
##### No Copy at All
Simple assignments make no copy of array objects or of their data.



In [126]:
a = np.arange(12)

In [127]:
b = a            # no new object is created

In [128]:
b is a           # a and b are two names for the same ndarray object

True

In [129]:
b.shape = 3,4    # changes the shape of a

In [130]:
a.shape

(3L, 4L)

Python passes mutable objects as references, so function calls make no copy.



In [131]:
def f(x):
    print(id(x))

In [132]:
id(a)                           # id is a unique identifier of an object

217127872L

In [133]:
f(a)

217127872


##### View or Shallow Copy
Different array objects can share the same data. The view method creates a new array object that looks at the same data.



In [134]:
c = a.view()

In [135]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
c is a

False

In [137]:
c.base is a                        # c is a view of the data owned by a

True

In [138]:
c.flags.owndata

False

In [139]:
c.shape = 2,6                      # a's shape doesn't change

In [140]:
a.shape

(3L, 4L)

In [141]:
c[0,4] = 1234                      # a's data changes

In [142]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

Slicing an array returns a view of it:



In [143]:
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"

In [144]:
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10

In [145]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

#### Deep Copy
The copy method makes a complete copy of the array and its data.



In [146]:
d = a.copy()                          # a new array object with new data is created

In [147]:
d is a

False

In [148]:
d.base is a                           # d doesn't share anything with a

False

In [149]:
d[0,0] = 9999

In [150]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

### Broadcasting rules

Broadcasting allows universal functions to deal in a meaningful way with inputs that do not have exactly the same shape.

The first rule of broadcasting is that if all input arrays do not have the same number of dimensions, a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

The second rule of broadcasting ensures that arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is assumed to be the same along that dimension for the “broadcast” array.

After application of the broadcasting rules, the sizes of all arrays must match.